// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACy4x8UtNW7G4wbXqce3Haze_FI1IAzLE',
    appId: '1:2479208409:web:ee092bd580fbd1e6e84bc8',
    messagingSenderId: '2479208409',
    projectId: 'petpals010',
    authDomain: 'petpals010.firebaseapp.com',
    storageBucket: 'petpals010.firebasestorage.app',
    measurementId: 'G-33K3Z5N2W9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7_mss8MblXonSebVOzLPIFAHJwFV80ps',
    appId: '1:2479208409:android:7cac8f586168b0f6e84bc8',
    messagingSenderId: '2479208409',
    projectId: 'petpals010',
    storageBucket: 'petpals010.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR-e9oAga6bGoNT1I4LIQI2V54MJUNdLI',
    appId: '1:2479208409:ios:651fb91f895d6aede84bc8',
    messagingSenderId: '2479208409',
    projectId: 'petpals010',
    storageBucket: 'petpals010.firebasestorage.app',
    iosBundleId: 'com.example.petpals',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDR-e9oAga6bGoNT1I4LIQI2V54MJUNdLI',
    appId: '1:2479208409:ios:651fb91f895d6aede84bc8',
    messagingSenderId: '2479208409',
    projectId: 'petpals010',
    storageBucket: 'petpals010.firebasestorage.app',
    iosBundleId: 'com.example.petpals',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACy4x8UtNW7G4wbXqce3Haze_FI1IAzLE',
    appId: '1:2479208409:web:bfa0e9a9ceb40b96e84bc8',
    messagingSenderId: '2479208409',
    projectId: 'petpals010',
    authDomain: 'petpals010.firebaseapp.com',
    storageBucket: 'petpals010.firebasestorage.app',
    measurementId: 'G-RQYPTL4MPW',
  );
}
